### ISSUE TITLE
drop_down_menus2.py Error messages during MagicGUI runtime

### ISSUE THREAD

**Issue by Caoimhinmg** [PmagPy/PmagPy#94]
So there are some new error messages being thrown by drop_down_menus2.py, I'm not sure if my recent edits to magic_grid2.py which altered how it reads jsons and grid_frame2 and 3 which were more aesthetic are in anyway a cause of this, but the errors do not cause failure of the program in anyway that I can see so far, everything was working when I tested basic functionality. As such I am just raising this issue as a reminder to myself or @moonshoes87 to look into this when there is time.

Traceback (most recent call last):
  File "dialogs/drop_down_menus2.py", line 78, in <lambda>
  File "dialogs/drop_down_menus2.py", line 270, in on_left_click
  File "pandas/core/generic.py", line 2672, in __getattr__
AttributeError: 'Series' object has no attribute 'insert'

Traceback (most recent call last):
  File "dialogs/drop_down_menus2.py", line 78, in <lambda>
  File "dialogs/drop_down_menus2.py", line 280, in on_left_click
  File "pandas/core/generic.py", line 2668, in __getattr__
AttributeError: 'Series' object has no attribute 'items'

**Comment by moonshoes87** [comment]
Thanks, I will work on this error soon.

**Comment by moonshoes87** [comment]
@Caoimhinmg, it's this commit that caused the error:  https://github.com/PmagPy/PmagPy/commit/94d11b7352b2ece52b3988a5986140ae1982659f

And there is broken functionality, which is that the drop-down menus don't work in the 2.5 version of MagIC GUI.  

In my code, I don't expect the 2.5 vocabulary stuff to be read in as pandas objects, so some things with the drop-down-menus.  Can you explain exactly what you were trying to fix with your changes in controlled_vocabularies2.py?  If needed I can redo the code in drop_down_menus to be compatible, but I'm confused as to why this change was made in the first place.

**Comment by Caoimhinmg** [comment]
@moonshoes87, thought it might be that. So the issue I was running into was during runtime of the frozen binary of MagIC GUI 2.5 was that pd.io.read_json, which was the old method of opening, would run into an internal runtime error in read_nonumpy something along the lines of:
```python
ValueError: "Expected value or object"
```
I had no idea what was up with this. So I checked out other people who had got this error and found that they mostly solved it by replacing read_json in the way you open the json in the 3.0 version of controlled vocabularies, which wasn't experiencing this error. So I took controlled vocabularies 3 and adapted the code into controlled vocabularies 2. Then I had some array problems so I cast it as a pandas DataFrame as I thought you were expecting a DataFrame as output. I suppose that instead I could just skip that step? Not sure what object you're expecting for those instance variables set in controlled_vocabularies2.Vocabulary.get_vocabularies.

Also how is the resizing of grid_frame working on mac, I couldn't test on OSX? I had to put that in because on linux (which uses an old version of wx) the scrolling wouldn't initialize when it was fixed size and it made MagIC GUI completely unusable. Plus I thought it'd be nice.

**Comment by moonshoes87** [comment]
The resizing caused one awkward display problem for grids with only one or two lines (they initialized way too big), which I believe I fixed without messing up the overall resizing.  Let me know if it still looks right on Linux.  Otherwise it looks good.  

I'll work out the controlled vocabularies 2 issue without pd.io.read_json.

**Comment by moonshoes87** [comment]
Pushing the fix.  The structure of vocabulary for 2.5 is just a dict of lists and dicts.  It uses dicts for really long vocabularies like lithology (over 100 items) that is then divided alphabetically to be a two-tiered drop-down-menu.  Let me know if this works correctly in Linux.

**Comment by Caoimhinmg** [comment]
Looks great over here, checked drop down boxes and resizing. Think we're in the clear on this. I'm closing the issue. 

Also cool thing for the issues I found out a little while ago, you can reference them in commits by mentioning the number of the issue like #XXX in the message and they get put in the issue time line between comments. You can also close issues with commits by putting the words resolved or fixed in the message along with the number of the issue. Thought it was interesting and you might find it useful.
